gsap.from("h2",{
    y:100,
    opacity:0,
    delay:0.5,
    duration:0.9,
    stagger:0.3
})
gsap.from("p",{
    z:100,
    opacity:0,
    delay:0.9,
    duration:0.9,
    stagger:0.3
})
gsap.from(".nav-button",{
    y:-50,
    opacity:0,
    delay:0.5,
    duration:0.9,
    stagger:0.3
})
gsap.from(".menu-icon",{
     y:-50,
    opacity:0,
    delay:0.5,
    duration:0.9,
    stagger:0.3
})